name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'r*' # Push events to matching v*, i.e. v1.0, v20.15.10
env: 
  GLOB_PATTERN: 'r[0-9][0-9][0-9][0-9]'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting Variables
        id: vars
        shell: bash
        run: |
          ref="$(cut -d'/' -f3 <<< ${{ github.ref }})"
          echo ${ref}
          echo "::set-env name=REV::${ref}"
          echo "이번 리비전: ${{ REV }}"
          echo "::set-env name=OLD_REV::${ref}"

      - name: Test
        shell: bash
        run: echo "${{ REV }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ REV }}
          body: |
            [Diff since ${{ OLD_REV }}](https://github.com/yongheekim-dev/GithubTagActionTest/compare/${{ steps.vars.outputs.OLD_REV }}...${{ REV }})
          draft: false
          prerelease: false