name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'r*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting Variables
        id: vars
        shell: bash
        run: |
          ref="$(cut -d'/' -f3 <<< ${{ github.ref }})"
          echo $ref
          echo "::set-output name=REV::${ref}"
          NUM=$(echo $ref | cut -c2-5)
          echo $NUM
          NUM=$(( NUM -1 ))
          echo $NUM
          NUM=$(printf "%04d\n" $NUM)
          echo $NUM
          echo "::set-output name=OLD_REV::r${NUM}"

      - name: Test
        shell: bash
        run: |
          echo "${{ steps.vars.outputs.REV }}"
          echo "${{ steps.vars.outputs.OLD_REV }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.vars.outputs.REV }}
          body: |
            [Diff ${{ steps.vars.outputs.OLD_REV }} to ${{ steps.vars.outputs.REV }}](https://github.com/yongheekim-dev/GithubTagActionTest/compare/${{ steps.vars.outputs.OLD_REV }}...${{ steps.vars.outputs.REV }})
          draft: false
          prerelease: false